language: node_js
node_js:
- latest
env:
  global:
  - secure: WXkeUKwWKTv2uUCyIiDdQ0e5gQCoX9gGj6wiNh9G7IATqcecxTw6cpQGj3J8YWDIjbtNXfAkJwohhGtXYr7VnkXRA1s0POYM+8cvM5I+ZDtZkXM9EvCwMYxf9XZ8qQ/4fegeSoZqfx1qgh+Sfh6Wp93I4W+AfB8VONLIGgXr172QGwYmkynPpC//mYA6sUZoQo4Y796PtBblc+7oM0a5A5chQ5r1CVqPqRZ/i9aNrH2UTdYjCMNE395LqwHSJGk5eunT5ebA4OcClme1wL78MJtGS1ZZIOEHSBv7mBrOcp29kYknc/m1PaOYBMdppmRBLr6Q5oUg8QzaILW2TypsWkosWpSlbemW1lsutqlFRkmtsjfX3ZVOoeIx/7J9v+pDA2gb7VMtNzwlkRpcLfHBmfuXuiPNXwLS1Ogl2D8JUD+rjwB3FI6pE2zZqNL7zMe7yhCQ/1wqGdlNqB1Ifb9T2RRkDCEUr+dw3sGn6Ecgk4XThUwY3vVzABj0C906Wc7UpsVvf1qjLCRg48lYG8kmhLqEylL+IUs3XXMSv69/YLxnDvRdF/d1FZHWKcoTeWYmXr3k1q0ePYEDXpX6/8MXWix1Qql4AAOjIxOgRufBPlDWe6QS2b97K4OPo+m3cf/RaLPz+jUOpf59l6CNnceBYLKs00Taf0KSgs+YVADAV6M=
before_script:
- git config --global user.email "basaratali@gmail.com"
- git config --global user.name "Travis-CI"
- git remote set-url origin https://github.com/basarat/monaco.git
script:
- bash prepare.sh
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git config --global push.default matching
- bash release.sh
branches:
  only:
  - master
deploy:
  provider: npm
  email: basaratali@gmail.com
  api_key:
    secure: h7yi0DpUP+uHggiTKghv2iao+m+nepyQh1szaC06FAjm2Xjc+P00lwym0z+1vUvitfYv/9AeEfAvoT9+efpIK8H3zlb96TOxAiOBHvgqNMkROawbNUdyN4UI6XlzHHeM7KidtzD6gG3x/HVGHAayl61k0dR5cV6Tc0aVdoWGmhvUiyjWeptzs/ev1ux3wwO3fKdUogy1whTwBUUzszLCIReugdda+eH93dbaWTw1TBZ69P7EOSyNUY9qEZx/7dP1xQ/j2/93Z2S8baEmK7MG/SeywEIHJX7CfG9Uzp6tJpr0l4hL/Q/TOrnXgoKuw8lKawvhQAxAy5T0RlP2fkLys4T6v9WcxKX9VBRsp+98pYgVflKIdzht9x+MD1kxuEB/kyhoNXkbRZN7EmN8j1mt+7l5m6mW2JPFm17e2/Q8kABy7EMmVjKh/NI3FL6eaCDfCHFXxrMbxdVbCw0f8CH2WX5rprwl+aLi1KTRqlzx+HbTqxEMkixbGOGLUkkUW9W/vNdg29x4InfNfnYa2oi78YchBTx9V7u0wd11Gxr1oMBtTNOnpUe7d8oA4/CinJFpnHW52JwyUDz9kyQsemkCyAP/eAVs5N1Ewh83IfndB9BymYm8Z8dTbgM1JvC6phhIYnWo23js6rCwH2DcN1NueKFu9fg80Ki7Q70fqKWB1Nk=
  on:
    repo: basarat/monaco
